# Generated by Django 5.0.1 on 2024-01-11 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos_and_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninja',
            name='desc',
            field=models.CharField(default='Old Dojo', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ninja',
            name='dojo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ninjas', to='dojos_and_ninjas_app.dojo'),
        ),
    ]
