# Generated by Django 5.0.1 on 2024-01-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos_and_ninjas_app', '0002_ninja_desc_alter_ninja_dojo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ninja',
            name='desc',
        ),
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.CharField(default='old dojo', max_length=255),
            preserve_default=False,
        ),
    ]
